const FETCH_CAT_FACTS = "FETCH_CAT_FACTS";
const FETCH_CAT_FACTS_ERROR = "FETCH_CAT_FACTS_ERROR";
const UPDATE_LOCAL_CAT_FACTS = "UPDATE_LOCAL_CAT_FACTS";
const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
const LOADING = "LOADING";

export {
  FETCH_CAT_FACTS_ERROR,
  FETCH_CAT_FACTS,
  UPDATE_LOCAL_CAT_FACTS,
  CHANGE_INPUT_VALUE,
  LOADING,
};
