const FETCH_CAT_FACTS = "FETCH_CAT_FACTS";
const UPDATE_LOCAL_CAT_FACTS = "UPDATE_LOCAL_CAT_FACTS";
const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";

export { FETCH_CAT_FACTS, UPDATE_LOCAL_CAT_FACTS, CHANGE_INPUT_VALUE };
