export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENTBYAMOUNT = 'INCREMENTBYAMOUNT';
export const NUMBERINFOLOADED = 'NUMBERINFOLOADED';
export const NUMBERINFOLOADFAILED = 'NUMBERINFOLOADFAILED';
